export var global = {
	url: 'http://172.17.2.81/api-rest-planes/public/api/',
	urlFile: 'http://172.17.2.81/api-rest-planes/storage/app/sop_mejoramiento/',
	checklist: [
		{id: 'checkbox1', value: 'JURIDICA', isSelected: false, text: 'Jurídica'},
		{id: 'checkbox2', value: 'COMUNICACIONES', isSelected: false, text: 'Comunicaciones'},
		{id: 'checkbox3', value: 'GESTION DEL CONOCIMIENTO', isSelected: false, text: 'Gestión del Conocimiento'},
		{id: 'checkbox4', value: 'CALIDAD', isSelected: false, text: 'Calidad'},
		{id: 'checkbox5', value: 'PARTICIPACION SOCIAL', isSelected: false, text: 'Participación Social'},
		{id: 'checkbox6', value: 'CONTROL INTERNO DISCIPLINARIO', isSelected: false, text: 'Control Interno Disciplinario'},//Esta mal escrito en la BD
		{id: 'checkbox7', value: 'SISTEMAS DE INFORMACION TICS', isSelected: false, text: 'Sistemas de Información TICS'},
		{id: 'checkbox8', value: 'DESARROLLO INSTITUCIONAL', isSelected: false, text: 'Desarrollo Institucional'},
		{id: 'checkbox9', value: 'DIRECCION AMBULATORIA', isSelected: false, text: 'Dirección Ambulatoria'},
		{id: 'checkbox10', value: 'DIRECCION URGENCIAS', isSelected: false, text: 'Dirección de Urgencias'},
		{id: 'checkbox11', value: 'DIRECCION GESTION DEL RIESGO', isSelected: false, text: 'Dirección Gestión del Riesgo'},
		{id: 'checkbox12', value: 'DIRECCION ADMINISTRATIVA', isSelected: false, text: 'Dirección Administrativa'},
		{id: 'checkbox13', value: 'DIRECCION CONTRATACION', isSelected: false, text: 'Dirección Contratación'},
		{id: 'checkbox14', value: 'DIRECCION HOSPITALARIA', isSelected: false, text: 'Dirección Hospitalaria'},
		{id: 'checkbox15', value: 'DIRECCION COMPLEMENTARIOS', isSelected: false, text: 'Dirección Complementarios'},
		{id: 'checkbox16', value: 'DIRECCION TALENTO HUMANO', isSelected: false, text: 'Dirección Talento Humano'},
		{id: 'checkbox17', value: 'DIRECCION FINANCIERA', isSelected: false, text: 'Dirección Financiera'}
	],
	optionList: [
		{value: 'ACREDITACION EN SALUD', text: 'Acreditación en Salud'},
		{value: 'ANALISIS EVENTOS ADVERSOS', text: 'Análisis de Eventos Adversos'},
		{value: 'ARCHIVO DISTRITAL', text: 'Archivo Distrital'},
		{value: 'AUTOEVALUACION ACREDITACION', text: 'Autoevaluación Acreditación'},
		{value: 'CONTRALORIA', text: 'Contraloría'},
		{value: 'CONTROL INTERNO', text: 'Control Interno'},
		{value: 'EPS', text: 'EPS'},
		{value: 'EPS CAPITAL SALUD', text: 'EPS Capital Salud'},
		{value: 'FONDO FINANCIERO DISTRITAL', text: 'Fondo Financiero Distrital'},
		{value: 'HABILITACION', text: 'Habilitación'},
		{value: 'INVIMA', text: 'INVIMA'},
		{value: 'ICONTEC', text: 'ICONTEC'},
		{value: 'PAMEC', text: 'PAMEC'},
		{value: 'PERSONERIA', text: 'Personería'},
		{value: 'REVISORIA FISCAL', text: 'Revisoría Fiscal'},
		{value: 'SDS', text: 'SDS'},
		{value: 'SUPER SALUD', text: 'Super Salud'},
		{value: 'VEEDURIA', text: 'Veeduría'}
	],
	accreditationTableList: [
		{value: 'MESA MEJORAMIENTO INSTITUCIONAL', text: 'Mesa Mejoramiento Institucional'},
		{value: 'MESA EQUIPO PRIMARIO URGENCIAS', text: 'Mesa Equipo Primario Urgencias'},
		{value: 'MESA EQUIPO PRIMARIO HOSPITALIZACION', text: 'Mesa Equipo Primario Hospitalización'},
		{value: 'MESA EQUIPO PRIMARIO CUIDADOS INTENSIVOS', text: 'Mesa Equipo Primario Cuidados Intensivos'},
		{value: 'MESA EQUIPO PRIMARIO CIRUGIA', text: 'Mesa Equipo Primario Cirugía'},
		{value: 'MESA EQUIPO PRIMARIO CONSULTA EXTERNA', text: 'Mesa Equipo Primario Consulta Externa'},
		{value: 'MESA EQUIPO PRIMARIO REHABILITACION', text: 'Mesa Equipo Primario Rehabilitación'},
		{value: 'MESA EQUIPO PRIMARIO ODONTOLOGIA', text: 'Mesa Equipo Primario Odontología'},
		{value: 'MESA EQUIPO PRIMARIO IMAGENOLOGIA', text: 'Mesa Equipo Primario Imagenología'},
		{value: 'MESA EQUIPO PRIMARIO LABORATORIO', text: 'Mesa Equipo Primario Laboratorio'},
		{value: 'MESA DIRECCIONAMIENTO Y GERENCIA', text: 'Mesa Direccionamiento y Gerencia'},
		{value: 'MESA GERENCIA TALENTO HUMANO', text: 'Mesa Gerencia Talento Humano'},
		{value: 'MESA GERENCIA AMBIENTE FISICO', text: 'Mesa Gerencia del Ambiente Físico'},
		{value: 'MESA GERENCIA TECNOLOGIA', text: 'Mesa Gerencia de la Tecnología'},
		{value: 'MESA GERENCIA INFORMACION', text: 'Mesa Gerencia de la Información'},
		{value: 'MESA PROMOCION Y DETECCION', text: 'Mesa Promoción y Detección'}
	],
	actionTypeList: [
		{value: 'PLANEAR'},
		{value: 'HACER'},
		{value: 'VERIFICAR'},
		{value: 'ACTUAR'}
	],
	fullfilmentTypeList: [
		{value: 'CUMPLIDA'},
		{value: 'PENDIENTE'}
	],
	findTypeList: [
		{value: 'AMBIENTAL', text: 'Ambiental', description: 'Relacionado con el proceso de Gestión Ambiental en la Subred Sur.'},
		{value: 'ARCHIVO', text: 'Archivo', description: 'Relacionado con el proceso de gestión documental.'},
		{value: 'COMUNICACIONES', text: 'Comunicaciones', description: 'Relacionado con el proceso de Gestión de Comunicaciones e Información Institucional.'},
		{value: 'DOTACION', text: 'Dotación', description: 'Relacionado con las condiciones, suficiencia y mantenimiento de los equipos biomédicos y mobiliario.'},
		{value: 'FINANCIERO', text: 'Financiero', description: 'Relacionado con el proceso de Gestión Financiera de la Subred Sur.'},
		{value: 'GESTION DE LA INFORMACION', text: 'Gestión de la Información', description: 'Relacionado con el proceso de Gestión de la Información que genera la Subred Sur con fines de uso interno y externo.'},
		{value: 'HISTORIA CLINICA Y REGISTRO', text: 'Historia Clínica y Registro', description: 'Relacionado con la existencia y cumplimiento de procesos, que garanticen la Historia Clínica por paciente y las condiciones técnicas de su manejo y el de los registros de procesos clínicos diferentes a la Historia Clínica que se relacionan directamente con los principales riesgos propios de la prestación de servicios.'},
		{value: 'INDICADORES', text: 'Indicadores', description: 'Relacionado con los indicadores asistenciales y administrativos de obligatorio cumplimiento.'},
		{value: 'INFRAESTRUCTURA', text: 'Infraestructura', description: 'Relacionado con las condiciones, suficiencia y el mantenimiento de la Infraestructura de las áreas asistenciales o características de ellas.'},
		{value: 'INTERDEPENDENCIA', text: 'Interdependencia', description: 'Relacionado con la existencia o disponibilidad de servicios o productos, propios o tercerizados, de apoyo asistencial o administrativo, necesarios para prestar en forma oportuna, segura e integral, los servicios ofertados.'},
		{value: 'MEDICAMENTOS', text: 'Medicamentos, Dispositivos Médicos e Insumos', description: 'Relacionado con procesos para la gestión de medicamentos, homeopáticos, Fito terapéuticos, productos biológicos, componentes anatómicos, dispositivos médicos, reactivos de diagnóstico in vitro, elementos de rayos x y de uso odontológico, así como de los demás insumos asistenciales que utilice la Institución.'},
		{value: 'OPORTUNIDAD', text: 'Oportunidad', description: 'Relacionado con la disponibilidad de agendas para la prestación de servicios asistenciales.'},
		{value: 'PROCESOS PRIORITARIOS', text: 'Procesos Prioritarios', description: 'Relacionado con la existencia, socialización y gestión del cumplimiento de los principales procesos asistenciales, que condicionan directamente la prestación con calidad y con el menor riesgo posible, en cada uno de los servicios de salud.'},
		{value: 'SISTEMAS TICS', text: 'Sistemas TICS', description: 'Relacionado con el proceso de Gestión de Sistemas de Información TICS.'},
		{value: 'TALENTO HUMANO', text: 'Talento Humano', description: 'Relacionado con las condiciones mínimas para el ejercicio profesional y ocupacional del Talento Humano asistencial y la suficiencia de este recurso para el volumen de la atención.'}
	],
	riskTypeList: [
		{value: 'AMBIENTAL', text: 'Riesgo Ambiental', description: 'Potenciales eventos asociados con afectaciones al medio ambiente.'},
		{value: 'CLINICOS', text: 'Riesgos Clínicos', description: 'Corresponden a los relacionados con los elementos, estructuras y procedimientos institucionales que afectan la atención del usuario y la comunidad y que pueden conducir a la prestación de incidentes o eventos adversos.'},
		{value: 'CORRUPCION', text: 'Riesgo Corrupción', description: 'Se entiende como la posibilidad de que por acción u omisión, mediante el uso indebido del poder, de los recursos o de la información, se desvíe la gestión de lo público, para la obtención de un beneficio particular.'},
		{value: 'ESTRATEGICOS', text: 'Riesgos Estratégicos', description: 'Son los relacionados con la Misión, el cumplimiento de los objetivos estratégicos y la definición de políticas.'},
		{value: 'FINANCIERO', text: 'Riesgo Financiero', description: 'Se relacionan con el manejo de los recursos de la entidad que incluye, la ejecución presupuestal, la elaboración de los estados financieros, los pagos, manejos de excedentes de tesorería y el manejo sobre los bienes de cada entidad. De la eficiencia y transparencia en el manejo de los recursos, así como su interacción con las demás áreas dependerá en gran parte el éxito o fracaso de toda entidad.'},
		{value: 'GERENCIA', text: 'Riesgo Gerencia', description: 'Posibilidad de ocurrencia de eventos que afecten los procesos gerenciales y/o la alta dirección.'},
		{value: 'LAFT', text: 'Riesgo LAFT', description: 'Eventos asociados con posible vinculación de oferentes o proveedores o contratistas en listas restrictivas a nivel nacional o internacional por Lavado de activos o financiación del terrorismo, y que potencialmente pretendan utilizar como fachada el nombre o vinculación con la institución para el desarrollo de posibles situaciones ilícitas.'},
		{value: 'LEGAL', text: 'Riesgo Legal', description: 'Se asocian con la capacidad de la entidad para cumplir con los requisitos legales, contractuales, de ética pública y en general con su compromiso ante la comunidad.'},
		{value: 'OPERATIVO', text: 'Riesgo Operativo', description: 'Comprenden riesgos provenientes del funcionamiento y operatividad de los procesos y/o articulación entre dependencias.'},
		{value: 'POBLACIONAL', text: 'Riesgo Poblacional', description: 'Corresponde a los relacionados con los factores determinantes que afectan la calidad de vida de grupos específicos con los cuales la institución asume la responsabilidad de intervención en salud.'},
		{value: 'REPUTACIONAL', text: 'Riesgo Reputacional', description: 'Están relacionados con la percepción y la confianza por parte de los grupos de interés hacia la institución.'},
		{value: 'SEGURIDAD INFORMATICA', text: 'Riesgo Seguridad Informática', description: 'Es el conjunto de medidas preventivas y reactivas de las organizaciones y de los sistemas tecnológicos que permitan resguardar y proteger la información buscando mantener la confidencialidad, la disponibilidad e integridad de la misma.'},
		{value: 'SEGURIDAD Y SALUD EN EL TRABAJO', text: 'Riesgo Seguridad y Salud en el Trabajo', description: 'Eventos que pueden afectar el bienestar físico, mental y social de los colaboradores.'},
		{value: 'TECNOLÓGICO', text: 'Riesgo Tecnológico', description: 'Se asocian con la capacidad de la Entidad para que la tecnología disponible satisfaga las necesidades actuales y futuras de la entidad y soporten el cumplimiento de la Misión.'}
	],
	permissionsList: [
		{value: 'ROLE_USER_1', text: 'Usuario Tipo I', description: 'Tiene acceso exclusivo a la creación de Oportunidades y Acciones de Mejora.'},
		{value: 'ROLE_USER_2', text: 'Usuario Tipo II', description: 'Tiene acceso al cargue de soporte para el cierre de acciones.'},
		{value: 'ROLE_USER_3', text: 'Usuario Tipo III', description: 'Tiene acceso exclusivo a la adición y edición de los Planes de Mejoramiento.'},
		{value: 'ROLE_ADMIN', text: 'Administrador', description: 'Administrador del aplicativo. Usualmente la persona encargada del proceso.'},
		{value: 'ROLE_SUPER_ADMIN', text: 'Super Administrador', description: 'Exclusivo del desarrollador o el encargado de Sistemas.'},		
	]
}